version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: bank_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pgdata:
