spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bankuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: my-super-secret-key-minimum-32-characters-long
    expiration-ms: 86400000